name: Upload to Play Store
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
permissions:
  contents: read
concurrency:
  group: "publish"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: "Google Play Upload"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle
      - run: ./gradlew app:bundleRelease
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ github.run_number }}
          ORG_GRADLE_PROJECT_version_name: ${{ github.ref_name }}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.pakohan.laundrytracker
          releaseFiles: app/release/app-release.aab
          track: qa
