name: Upload to Play Store
on:
  push:
    branches:
      - main
permissions:
  contents: write
concurrency:
  group: "publish"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: "Google Play Upload"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle
      - run: ./gradlew app:bundleRelease
        env:
          ORG_GRADLE_PROJECT_version_code: ${{ github.run_number }}
          ORG_GRADLE_PROJECT_version_name: $(git rev-parse --short "$GITHUB_SHA")
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.run_number }}
          generate_release_notes: true
          make_latest: true
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.pakohan.laundrytracker
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: internal
          status: draft
