name: Gradle Tests
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency:
  group: "test"
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew test
